version: '3'

services:
  db:
    image: work21-docker
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:80000
    ports:
      - '8000:8000'
    depends_on:
      - db